### ISSUE TITLE
[Bug]: All Dynamic Tests cannot be executed; Received message" Unsupported test type"

### ISSUE THREAD

**Issue by shattenjager** [ghostsecurity/reaper#150]
### Summary

When attempting to create a new dynamic test, on any endpoint the result is always a "Unsupported test type" message.

### Page

http://localhost:8000/test

### Details

It's not possible to create and run ANY test on ANY endpoint:
![image](https://github.com/user-attachments/assets/dc7d91c8-0da6-4108-a715-89b063a0c74d)

I tried 2 different hosts but no luck so far

### Contact Email

thomas@mastodonsec.com

**Comment by joshlarsen** [comment]
Hi @shattenjager,

The only test type supported currently is "IDOR/BOLA". However, this test requires an endpoint that has body parameters to tamper. In your screenshot, you are targeting a `GET` request to a static `.js` file, which has no parameters.

If you choose a `POST` request with body parameters, you'll see something like the image below. Where you can select which parameters to target. Hope that helps!

<img width="475" alt="image" src="https://github.com/user-attachments/assets/3581bcfb-8978-470c-bdb0-ed0732bd3897">

**Comment by shattenjager** [comment]
Thank you and sorry for the super late reply, I was deployed oversea and completely forgot to follow up! And you are right, the screenshot was showing a GET request, my bad!!
