### ISSUE TITLE
docs: "build from source" link 404's

### ISSUE THREAD

**Issue by raesene** [ghostsecurity/reaper#85]
Browsing to https://ghostsecurity.github.io/reaper/getting-started/installation , then following the link for "build from source" leads to a 404 with a URL of https://ghostsecurity.github.io/reaper/getting-started/source

Following the link from the Table Of Contents section below that, to "From Source" works, with a URL of https://ghostsecurity.github.io/reaper/getting-started/installation/source

**Comment by liamg** [comment]
Hey @raesene - good to see you! Thanks for the bug report :)
