### ISSUE TITLE
Hello from Caido 👋 

### ISSUE THREAD

**Issue by Sytten** [ghostsecurity/reaper#87]
Hello there!

Seems like we are building a similar tool, good to see some competition to Burp Suite dominance 😃 
We started working on workflows too, I believe this is the future.
Maybe could be cool to build a shared format/syntax for it? It me up if you are interested!

I wish you guys all the best, it's not an easy road! 
We have been at it for a couple years now so I know the pain ahead very well 😅

**Comment by psiinon** [comment]
Hi from the ZAP team ⚡  😁 
We're always on for shared formats/standards ...

**Comment by joshlarsen** [comment]
👻 boo

**Comment by psiinon** [comment]
@Sytten Definitely! Contact details on https://www.zaproxy.org/docs/team/psiinon/

**Comment by padsalatushal** [comment]
love to see zapproxy,caido and ghostsecurity and others to work together to develop better things for community.
@psiinon @Sytten @joshlarsen
